"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PekmanAnalyzer.py']
DATA_FILES = ['icon.ico']
OPTIONS = {'iconfile': '/Users/dianarom/Desktop/Pekman_analyzer/icon.ico'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
